c: 
  - 5
  - 6
  - 7
  - 8
i:
  - 2
  - 3
  - 4
n:
  - 24
  - 49
  - 74
  - 99
prws_aln_meth:
  - sw_pair
  - lalign_id_pair
  - blast_pair
ref_pdb: 7Z09
ref_lysine_pos: 207 # original pos K216
br_prefix_n: 14
br_suffix_c: 10
max_missing_n: 10
max_missing_c: 8
min_len: 180
max_len: 299
max_rmsd: 3.8
min_align_len: 180
max_query_len: 300
query_padding: 10
